### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by lenormf** [tuur29/fuzzyclock#86]
Hi,

I like to use the Google Play Store as little as possible, would you consider publishing released on [F-Droid](https://f-droid.org/) as well? Your app would be a great fit for this open-source store.

Thanks!

**Comment by tuur29** [comment]
Good point, never thought of uploading it there as well. I'll take a look at it and let you know!

**Comment by lenormf** [comment]
Great, thanks. Feel free to close this issue once you've reached a conclusion.

**Comment by tuur29** [comment]
While I agree that it would definitely fit there, the submit process seems overly complex. After an hour of research I've only gotten the basics.

These 3 apps combined only have around ~150 active users on the google play store so I don't see the likely day(s) I will spend on this being worth it.

**Comment by lenormf** [comment]
The [contribution guidelines](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md) seem straight forward, there have to be some constraints on submission otherwise the store couldn't keep its standards of quality :)

I thought this would take one rainy sunday afternoon to handle, maybe you'll have one of these soon?

**Comment by tuur29** [comment]
Hmm, I'll keep a note of it on my board for later.
Those sundays you speak of have been blocked off for other similar projects lately. I'll update the ticket if I ever get around to it.
